name: Build & Test

on:
  pull_request:
  workflow_dispatch:
  workflow_call: {}

jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup .NET environment
        uses: ./.github/actions/setup-dotnet-env

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release -p:Platform=x64 -p:AppxPackageSigningEnabled=false

      - name: Test
        run: dotnet test --no-build --configuration Release -p:Platform=x64 --logger GitHubActions
